services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pantog
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - backend 
    ports:
      - "5432:5432" 

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - backend

  pantog:
    build: ./api
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - POSTGRES_DSN=host=postgres user=postgres password=postgres dbname=pantog port=5432 sslmode=disable
      - REDIS_ADDR=redis:6379
    networks:
      - backend

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./web:/usr/share/nginx/html
    depends_on:
      - pantog
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
